import Head from "next/head";
import Button from "@mui/material/Button";
import { useState } from "react";
import { ethers } from "ethers";
import { TextField } from "@mui/material";

export default function Home() {
  const [account, setAccount] = useState("0x0000");

  const [isConnected, setIsConected] = useState(false);

  const connectWallet = async () => {
    if (window.ethereum == null) {
      console.log("MetaMask not installed");
    } else {
      try {
        const provider = new ethers.BrowserProvider(window.ethereum);

        const signer = await provider.getSigner();

        setIsConected(true);
        setAccount(signer.address);
      } catch (error) {
        console.log("Error connection...");
      }
    }
  };

  return (
    <>
      <Head>
        <title>Token Sale</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="bg-black w-full h-screen flex items-center justify-center">
          <h4 className="absolute top-6 left-6 text-blue-600">
            Your address: {account}
          </h4>
          <div className="absolute top-6 right-6">
            <Button
              variant="outlined"
              onClick={connectWallet}
            >
              Connect wallet
            </Button>
          </div>

          <div className="w-[450px] h-[300px] text-center border-[1px] border-blue-700 rounded-[18px]">
            {!isConnected ? (
              <h1 className="text-center text-blue-600 text-3xl mt-[30%] justify-center">
                Please connect your wallet
              </h1>
            ) : (
              <div>
                {/* <TextField className="" id="outlined-basic" label="Value in BNB" variant="outlined" />
                <Button variant="contained" color="secondary">Buy</Button> */}
              </div>
            )}
          </div>
        </div>
      </main>
    </>
  );
}
